### ISSUE TITLE
destroying VM works, but throws error

### ISSUE THREAD

**Issue by wdeviers** [CenturyLinkCloud/chef-provisioning-vsphere#21]
I've been hacking around trying to figure out how to make a generic provisioning system out of this, and I've made a lot of progress. Running a clean gem pull from today using chef_gem, I'm creating a series of machines like:
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/RS-Provisioning/recipes/default.rb
    
     85:   machine "microtest#{count}" do
     86:     my_ip[count] = {
     87:       bootstrap_options: {
     88:         customization_spec: {
     89:           ipsettings: {
     90:             ip: "10.132.21.#{count}"
     91:           }
     92:         }
     93:       }
     94:     }
     95:     new_options[count] = Chef::Mixin::DeepMerge.deep_merge(default_options,my_ip[count])
     96:     name "microtest#{count}"
     97:     run_list ['RS-DCS-Base']
     98:     machine_options new_options[count]
     99:     action :ready
    100:   end
    101: end

to just quickly spin 5 machines.  It works fine.  I then replace ready with destroy.  The first VM powers down and is deleted by vcenter as expected, but throws a:

Net::HTTPServerException
    ------------------------
    chef_client[microtest105] (basic_chef_client::block line 26) had an error: Net::HTTPServerException: 403 "Forbidden"

First part of the trace looks like:
```
Generated at 2015-08-12 16:19:17 -0400
Net::HTTPServerException: machine[microtest105] (RS-Provisioning::default line 85) had an error: Net::HTTPServerException: chef_client[microtest105] (basic_chef_client::block line 26) had an error: Net::HTTPServerException: 403 "Forbidden"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:145:in `request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:110:in `get'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/actor_provider_base.rb:117:in `load_current_resource'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:113:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/basic_chef_client.rb:69:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/basic_chef_client.rb:133:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/basic_chef_client.rb:133:in `with_chef_config'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/basic_chef_client.rb:68:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.2.1/lib/cheffish/basic_chef_client.rb:109:in `converge_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning.rb:12:in `inline_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provisioning/convergence_strategy/no_converge.rb:21:in `cleanup_convergence'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-vsphere-0.7.1/lib/chef/provisioning/vsphere_driver/driver.rb:392:in `destroy_machine'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.3.0/lib/chef/provider/machine.rb:95:in `block in <class:Machine>'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
```

Each chef-client run then deletes one more, as expected, then 403's.  The 403 return is instantaneous, meanwhile the VCenter delete obviously takes a few seconds (10-15ish).

I'll try to dig in but I've run out of time on this for the moment.

Thanks for the good work; I'm really glad I ran across this gem.

Wes

**Comment by wdeviers** [comment]
In one of those "doh" moments I realized, after looking at this for 30 minutes, that the 403 is getting thrown by Chef Server, not VCenter.  Looking into my ACL setup.

**Comment by wdeviers** [comment]
Only slightly embarrassing.  The problem is that the node I was running chef-client from can create nodes and clients, can delete nodes (because the nodes it creates are owned by it), but has no permission to delete *clients*.  Our ACLs are funky. Leaving this here in case other people run across the problem

```bash
knife group add client client.running.provisioning admins
```
or you could build up real ACLs and create a provisioning group that has correct permissions and cascade it out.
