### ISSUE TITLE
Warnings after kitchen create

### ISSUE THREAD

**Issue by PrahlM93** [CenturyLinkCloud/chef-provisioning-vsphere#54]
Hello,
I am currently using the chef-provisioning-vsphere as a Test-Kitchen driver for my PowerShell Desired State Configuraiton integration tests. With that said, I am not configuring anything related to Chef which may be the issue.

After running "kitchen create" and the machine is deployed, I get the following Warning:
```
[2016-01-26T15:04:12-05:00] WARN: chef_environment nil currently does not overwrite the value of chef_environment. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :chef_environment, [MyType, nil]", or stop setting this value to nil. at C:/Users/user/AppData/Local/chefdk/gem/ruby/2.1.0/gems/cheffish-1.6.0/lib/chef/resource/chef_node.rb:15:in `initialize'
[2016-01-26T15:04:12-05:00] WARN: chef_environment nil currently does not overwrite the value of chef_environment. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :chef_environment, [MyType, nil]", or stop setting this value to nil. at C:/Users/user/AppData/Local/chefdk/gem/ruby/2.1.0/gems/cheffish-1.6.0/lib/chef/resource/chef_node.rb:15:in `initialize'
create node AddDomain-win2012r2-vsphere-9cfcea12 at chefzero://localhost:8889
  add normal.chef_provisioning = {"reference"=>{"driver_url"=>"vsphere://vsphere.somedomain.com/sdk?use_ssl=true&insecure=true", "driver_version"=>"0.8.3", "server_id"=>"268f2518-cbcf-453c-9935-515b99bee089", "is_windows"=>true, "allocated_at"=>"2016-01-26 20:03:05 UTC", "ipaddress"=>"192.168.1.100"}}
  add normal.tags = nil
```

Here is the vsphere configuration in my .kitchen.yml file:
```
platforms:
  - name: win2012r2-vsphere
    driver_plugin: vsphere
    driver_config:
      driver_options:
        host: 'vsphere.somedomain.com'
        user: <%= ENV['VSPHERE_USER'] %>
        password: <%= ENV['VSPHERE_PASSWORD'] %>
        insecure: true
      machine_options:
        ready_timeout: 180
        bootstrap_options:
          use_linked_clone: true
          datacenter: 'Some Datacenter'
          template_name: 'win12r2wmf5'
          template_folder: 'DSC'
          vm_folder: 'DSC'
          ssh:
            user: vagrant
            password: vagrant
```

I appreciate any help, and thank you for this plugin, it is fantastic.

**Comment by PrahlM93** [comment]
Upgrading Test-Kitchen fixed the issue.
