### ISSUE TITLE
create_ssh_transport should use hash instead of Cheffish::MergedConfig

### ISSUE THREAD

**Issue by chrodriguez** [CenturyLinkCloud/chef-provisioning-vsphere#59]
When creating a new VM and it's in a ready state, chef-provisioning tries to create a transport and it fails with the following error:

```
    NoMethodError
    -------------
    Unexpected method delete for MergedConfig with arguments [:remote_forwards]

```
The relevant lines from chef stacktrace are:

```
NoMethodError: machine[supermarket] (cespi_clusters::management line 8) had an error: NoMethodError: Unexpected method delete for MergedConfig with arguments [:remote_forwards]
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-2.0.2/lib/cheffish/merged_config.rb:50:in `method_missing'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provisioning/transport/ssh.rb:45:in `initialize'
/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:662:in `new'
/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:662:in `create_ssh_transport'/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:638:in `transport_for'
/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:612:in `wait_for_transport'
/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:284:in `transport_respond?'
/home/car/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.3/lib/chef/provisioning/vsphere_driver/driver.rb:209:in `ready_machine'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider.rb:360:in `instance_eval'

``` 

Following the code, I think there is a problem at [lib/chef/provisioning/vsphere_driver/driver.rb#L665](https://github.com/chrodriguez/chef-provisioning-vsphere/blob/master/lib/chef/provisioning/vsphere_driver/driver.rb#L665)
The problem seems to be that the options is a Cheffish::MergedConfig object and it doesn't implements a `#delete` as can be seen in [chef provisioning gem implementation](https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/transport/ssh.rb#L45)

So, I propose to change

```ruby
    def create_ssh_transport(host, options)
      require 'chef/provisioning/transport/ssh'
      ssh_user = options[:user]
      Chef::Provisioning::Transport::SSH.new(
        host,
        ssh_user,
        options,
        @config[:machine_options][:sudo] ? {:prefix => 'sudo '} : {},
        config
      )
    end
```

With

```ruby
    def create_ssh_transport(host, options)
      require 'chef/provisioning/transport/ssh'
      ssh_user = options[:user]
      Chef::Provisioning::Transport::SSH.new(
        host,
        ssh_user,
        options.to_hash,
        @config[:machine_options][:sudo] ? {:prefix => 'sudo '} : {},
        config
      )
    end
```

**Comment by chrodriguez** [comment]
Thanks!
