### ISSUE TITLE
Required property fullName is missing from data object of type CustomizationUserData

### ISSUE THREAD

**Issue by ktlim86** [CenturyLinkCloud/chef-provisioning-vsphere#64]
Hi all,

I am new to Chef. I have tried to provision a VM using a VM template that I have created in the vSphere client using the Chef provisioner. I have setup my own Chef Server and upload the cookbook into my Chef server.

I have encountered an issue while I was executing this command:
`chef-client -o 'setup_vm::default' -c .\.chef\knife.rb` 

the output of the message looks like this from chef-stacktrace.out:
```
Generated at 2016-03-29 17:26:16 +0800
RbVmomi::Fault: machine[server01] (setup_vm::default line 48) had an error: RbVmomi::Fault: InvalidRequest: 
Required property fullName is missing from data object of type CustomizationUserData

while parsing serialized DataObject of type vim.vm.customization.UserData
at line 1, column 1086

while parsing property "userData" of static type CustomizationUserData

while parsing serialized DataObject of type vim.vm.customization.Sysprep
at line 1, column 784

while parsing property "identity" of static type CustomizationIdentitySettings

while parsing serialized DataObject of type vim.vm.customization.Specification
at line 1, column 740

while parsing property "customization" of static type CustomizationSpec

while parsing serialized DataObject of type vim.vm.CloneSpec
at line 1, column 312

while parsing call information for method CloneVM_Task
at line 1, column 177

while parsing SOAP body
at line 1, column 167

while parsing SOAP envelope
at line 1, column 0

while parsing HTTP request for method clone
on object of type vim.VirtualMachine
at line 1, column 0
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:61:in `parse_response'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:90:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:511:in `clone_vm'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:31:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:38:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_ready'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
(eval):2:in `block in action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:412:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/embedded/bin/chef-client:22:in `load'
C:/opscode/chefdk/embedded/bin/chef-client:22:in `<main>'
```

```
chef_gem 'chef-provisioning-vsphere' do
  action :install
  compile_time true
end

require 'chef/provisioning/vsphere_driver'

with_vsphere_driver host: 'MY_VSPHERE_CENTER_IP',
  insecure: true,
  user:     'MY_VSPHERE_USER',
  password: 'MY_PASSWORD'

with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 2,
  host: 'MY_VSPHERE_HOST_IP',
  memory_mb: 4096,
  #network_name: ["vlan_internet"],
  datacenter: 'dc',
  template_name: 'BaseWindows2012R2',
  customization_spec: {
    ip: 'MY_ASSIGNED_HOST_IP',
    subnetMask: 'MY_SUBNET',
    gateway: 'MY_GATEWAY_IP',
    ipsettings: {
      dnsServerList: ['DNS_1','DNS_2']
    },
    win_time_zone: 215,
    domain: 'local'
  },
  :ssh => {
    :user => 'MY_WINDOWS_USER',
    :password => 'MY_PASSWORD',
    :paranoid => false,
  }
}

machine "server01" do
  run_list ['setup_vm::default']
end
```

Any ideas how do I solve it? 
Thanks.

**Comment by ktlim86** [comment]
ok I have managed to resolve it by adding the `org_name` and `product_id` inside the `default.rb`.
here is the final one.

```
chef_gem 'chef-provisioning-vsphere' do
  action :install
  compile_time true
end

require 'chef/provisioning/vsphere_driver'

with_vsphere_driver host: 'MY_VSPHERE_CENTER_IP',
  insecure: true,
  user:     'MY_VSPHERE_USER',
  password: 'MY_PASSWORD'

with_machine_options :bootstrap_options => {
  use_linked_clone: true,
  num_cpus: 2,
  host: 'MY_VSPHERE_HOST_IP',
  memory_mb: 4096,
  #network_name: ["vlan_internet"],
  datacenter: 'dc',
  template_name: 'BaseWindows2012R2',
  customization_spec: {
    ip: 'MY_ASSIGNED_HOST_IP',
    subnetMask: 'MY_SUBNET',
    gateway: 'MY_GATEWAY_IP',
    ipsettings: {
      dnsServerList: ['DNS_1','DNS_2']
    },
    win_time_zone: 215,
    org_name: 'my_org',
    product_id: '',
    domain: 'local'
  },
  :ssh => {
    :user => 'MY_WINDOWS_USER',
    :password => 'MY_PASSWORD',
    :paranoid => false,
  }
}

machine "server01" do
  run_list ['setup_vm::default']
end
```

now i have a new error
```
Generated at 2016-03-29 17:53:11 +0800
RbVmomi::Fault: machine[server01] (setup_vm::default line 50) had an error: RbVmomi::Fault: CannotAccessVmConfig: Unable to access the virtual machine configuration: Unable to access file [dev_lun01] BaseWindows2012R2/BaseWindows2012R2.vmtx
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:515:in `clone_vm'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:177:in `find_or_create_vm'
C:/Users/iMerino/AppData/Local/chefdk/gem/ruby/2.1.0/gems/chef-provisioning-vsphere-0.8.4/lib/chef/provisioning/vsphere_driver/driver.rb:135:in `allocate_machine'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:31:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_allocate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:38:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_ready'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.6.0/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
(eval):2:in `block in action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `instance_eval'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:360:in `compile_and_converge_action'
(eval):2:in `action_converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:412:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/embedded/bin/chef-client:22:in `load'
C:/opscode/chefdk/embedded/bin/chef-client:22:in `<main>'
```

any ideas how should I solve it?
Thanks.

**Comment by mwrock** [comment]
Never seen that error before. You might have a look at https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003795. Also I'd be curious if you can clone from the same template using just the vsphere client.

**Comment by ktlim86** [comment]
Hi mwrock,

Thanks. I managed to solve it by shifting my VM template file to the ESXI host that I want to host the VM and it works. I realized that my base VM template is different datastore and hence this explaieds the above error.
